

# Elements and component attributes
# =================================

diagram:
  tag: pinout

text: &text
    fill: [0, 0, 0]
    family: Verdana, Geneva, sans-serif
    size: 12
    weight: normal

# information-panel
infpanel_rect: &infpanel
  fill: [255, 250, 245]
  stroke: [204, 204, 204]
  stroke_width: 1
  rx: 0

rect: &rect
  fill: [244, 244, 244]
  stroke: [204, 204, 204]
  stroke_width: 1
  rx: 0

path:
  stroke: [204, 204, 204]
  stroke_width: 3


label:
  rect:
    << : *rect
    height: 28
    width: 60
    rx: 4
    stroke_width: 1
  text: 
    << : *text


legend:
  padding: [15, 30]
  row_height: 30
  tag: legend
  rect:
    << : *infpanel
    # height dynamically calculated
    width: 300
  text:
    fill: [0,0,0]
    family: Verdana, Geneva, sans-serif
    size: 12
    weight: bold


pinlabel:
  offset: [12,0]
  tag: pl
  label:
    text:
      fill: [255,255,255]
      family: Verdana, Geneva, sans-serif
      size: 12
      weight: normal
    rect:
      fill: [0, 0, 0]
      height: 26
      rx: 2
      stroke: [204, 204, 204]
      stroke_width: 0
      width: 50
  leaderline:
    stroke: [204, 204, 204]
    stroke_width: 1
    tag: ll


pinlabelrow:
  tag: pl-row


leaderline:
  stroke: [204, 204, 204]
  stroke_width: 1
  tag: ll


informationpanel:
  tag: inf
  fill: [255,255,255]
  stroke: [225, 225, 225]
  stroke_width: 3
  rx: 4

annotation:
  offset: [50,-50]
  label:
    text: 
      << : *text
      size: 14
    rect:
      fill: [244, 244, 244]
      height: 30
      rx: 4
      stroke: [204, 204, 204]
      stroke_width: 3
      width: 100
  leaderline:
    stroke: [204, 204, 204]
    stroke_width: 5


# Tag styleguide
# ================================
# <tag> tag identifier (must be CSS compliant name)
# <title> text representation in legend
# <color> RGB color representation

tags:
    # <tag>
      # title: <title>
      # color: [<0-255>, <0-255>, <0-255>]
    analog:
      title: Analog
      color: [215, 107, 173]
    comms:
      title: Communication
      color: [203, 116, 16]
    gpio:
      title: GPIO
      color: [44, 91, 123]
    pwr:
      title: Power management
      color: [150, 2, 29]
    pwm:
      title: PWM
      color: [54, 157, 158]
    led:
      title: LED
      color: [162, 179, 55]
