
diagram:
  tag: pinout
  text: 
    color: [0,0,0]
    family: Verdana, Geneva, sans-serif
    size: 14
    weight: bold

legend:
  categories: [
    # [<Title>, <CSS class 'tag'>]
    ["Analog", "analog"],
    ["Communication", "comms"],
    ["GPIO", "gpio"],
    ["Power management", "pwr"],
    ["PWM", "pwm"],
  ]
  # padding: [15, 30]
  row_height: 30
  tag: legend
  text:
    color: [0,0,0]
    family: Verdana, Geneva, sans-serif
    size: 12
    weight: bold
  width: 300

pinlabel:
  box:
    offset: [15,0]
    height: 28
    width: 70
  tag: pl
  text:
    color: [255, 255, 255]
    family: Verdana, Geneva, sans-serif
    size: 12
    weight: normal

pinlabelrow:
  leaderline:
    stroke-width: 2
  tag: pl-row